add ChangeCppPropertiesRequest and remove Notification.
microsoft/vscode-cpptools pull request #10420
Opened 2023-01-25 23:26 UTC by browntarik

2023-01-25 23:56 UTC, sean-mcmanus submitted a review, later dismissed

2023-01-26 02:46 UTC, Colengms requested changes

2023-01-26 02:46 UTC, Colengms commented on Extension/src/LanguageServer/client.ts
> +const ChangeCppPropertiesRequest: RequestType<CppPropertiesParams, void, void> = new RequestType<CppPropertiesParams, void, void>('cpptools/didChangeCppProperties');
This requires a corresponding change on the native side as well, as it will need to call `queue_server_response` to indicates it's done.

2023-01-27 01:45 UTC, sean-mcmanus approved these changes

2023-01-27 01:45 UTC, Colengms approved these changes

2023-01-27 01:45 UTC, michelleangela approved these changes

2023-01-27 01:51 UTC, merged