Add Ada to the list of supported languages (#10475)
microsoft/vscode-cpptools pull request #10476
Opened 2023-02-06 14:09 UTC by AnthonyLeonardoGracio

To allow debugging Ada projects with GDB.

2023-02-06 19:14 UTC, sean-mcmanus requested changes

2023-02-06 19:14 UTC, sean-mcmanus commented on Extension/package.json
> +          "ada",
Can you move this below "rust"? Unless the order is supposed to be alphabetical?

2023-02-06 19:56 UTC, WardenGnaw approved these changes

2023-02-06 23:01 UTC, sean-mcmanus commented
@WardenGnaw Should we add Fortran too? I noticed https://github.com/microsoft/vscode-cpptools/issues/10406 .

2023-02-07 09:21 UTC, AnthonyLeonardoGracio commented on Extension/package.json
> +          "ada",
I think it's alphabetical yes. It probably does not change the extension's behavior in any case.

2023-02-07 20:41 UTC, WardenGnaw commented
> @WardenGnaw Should we add Fortran too? I noticed #10406 .

I would only add it if we have a request. GDB supports the following languages C, C ++, D, Go, Objective-C,  Fortran, Pascal, Rust, Assembly, Modula-2, and Ada.

I'm hesitant on adding everything unless there is a request for it.

2023-02-07 20:56 UTC, sean-mcmanus approved these changes

2023-02-09 01:41 UTC, merged