Refactor experiment variable
microsoft/vscode-cpptools pull request #10717
Opened 2023-03-21 16:57 UTC by bobbrow

Move logic for experiments into the telemetry module closer to the experimentation service. This is to set the pattern for future experiments so that they are all defined in the same place.

2023-03-21 17:07 UTC, sean-mcmanus requested changes

2023-03-21 17:07 UTC, sean-mcmanus commented on Extension/src/telemetry.ts
> +    const experimentationService: IExperimentationService | undefined = await getExperimentationService();
Can you check the setting first? i.e.
```ts
    if (new CppSettings().experimentalFeatures) {
        return true;
    }
    const experimentationService: IExperimentationService | undefined = await getExperimentationService();
    const useNewUI: boolean | undefined = experimentationService?.getTreatmentVariable<boolean>("vscode", "ShowLangStatBar");
    return useNewUI ?? false;
```

2023-03-21 18:10 UTC, bobbrow commented on Extension/src/telemetry.ts
> +    const experimentationService: IExperimentationService | undefined = await getExperimentationService();
sure

2023-03-22 00:34 UTC, michelleangela approved these changes

2023-03-22 01:35 UTC, sean-mcmanus approved these changes

2023-03-22 01:35 UTC, merged