Update WSL config docs
microsoft/vscode-cpptools pull request #1176
Opened 2017-10-28 00:28 UTC by mezzode

Docs needed an updated since the current version of WSL from the Fall Creators Update needs a different configuration to the beta version.

It does feel kind of wrong having a path going inside a Windows App folder, but it works. I wonder whether WSL should add some environment variables for `rootfs` instead, though thats not really an issue for this repo.

2017-10-28 00:29 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Microsoft/vscode-cpptools?pullRequest=1176) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Microsoft/vscode-cpptools?pullRequest=1176) before we can accept your contribution.<br/><br/>:x: mezzode [sign now](https://cla.opensource.microsoft.com/Microsoft/vscode-cpptools?pullRequest=1176)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Microsoft/vscode-cpptools?pullRequest=1176) it.</sub>

2017-10-28 00:33 UTC, mezzode commented
Related Microsoft/WSL#2578

2017-10-30 16:03 UTC, bobbrow commented on Documentation/LanguageServer/Windows Subsystem for Linux.md
> +        "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
these look like the old paths.

2017-10-30 16:05 UTC, bobbrow commented on Documentation/LanguageServer/Windows Subsystem for Linux.md
> +        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5",
So this works for Ubuntu, but what about OpenSUSE and SLES which are also available in the Windows Store?  Should we provide configs for each of them?

2017-10-30 16:08 UTC, bobbrow requested changes
I suspect that Ubuntu will be the most popular choice, but we should probably talk about the other distros as well.  If you don't have time to test them out yourself, can you just add a note that the paths will be different for the other distros?

2017-10-31 00:22 UTC, mezzode commented
I already put a note about other distros on [line 48](https://github.com/Microsoft/vscode-cpptools/pull/1176/files/9556593ce90fba74c77493ab7a42ba687bde92a2#diff-5537677e739ef549c6620b2c35b674d9R48).
> Note that `${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/` is the path to the root of the Ubuntu filesystem. This will be different if you are using a different distro.

2017-10-31 04:02 UTC, icylogic commented
We can generate paths by
```Powershell
PS R:\> ($(get-appxpackage).PackageFamilyName | findstr 'SUSE Ubuntu') -replace '^', "$`{localappdata`}\Packages\"

${localappdata}\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
${localappdata}\Packages\46932SUSE.openSUSELeap42.2_022rs5jcyhyac
${localappdata}\Packages\46932SUSE.SUSELinuxEnterpriseServer12SP2_022rs5jcyhyac

```
Even for Fedora and any other subsystems in the future.

2017-10-31 16:33 UTC, bobbrow approved these changes

2017-10-31 16:33 UTC, merged

2017-10-31 16:39 UTC, bobbrow commented
Thanks @icylogic. I included your Powershell command in the doc.