Add Fragments field to task.json to persist legacy command line argument behavior.
microsoft/vscode-cpptools pull request #12003
Opened 2024-02-22 23:08 UTC by browntarik

Addresses: https://github.com/microsoft/vscode-cpptools/issues/12001

2024-02-22 23:25 UTC, sean-mcmanus commented on Extension/src/LanguageServer/cppBuildTaskProvider.ts
>                  args: args,
pre-existing issue, but I think this can be simplified to

```
args,
fragments,
options
```

2024-02-22 23:28 UTC, sean-mcmanus approved these changes

2024-02-23 02:56 UTC, Colengms requested changes

2024-02-23 02:56 UTC, Colengms commented on Extension/package.nls.json
> +    "c_cpp.taskDefinitions.fragments.description": "Additional arguments to pass to the compiler that are expected to receive shell processing. For example, '*.c' should expand to all .c files in the
The Windows command prompt doesn't do wildcard expansion. I'd omit the example. 

How about? :  `Command line fragments to pass to the compiler or compilation script. These arguments will receive limited shell command line processing. Multiple arguments may be specified per value.`

And maybe update `args` to, `Arguments to pass to the compiler or compilation script. These are not expected to contain shell escaping and will not receive shell processing. A single argument should be specified per value`.

(The use of `Additional` in the descriptions seems unnecessary to me.)

2024-02-23 02:56 UTC, Colengms commented on Extension/src/LanguageServer/cppBuildTaskProvider.ts
> +        if (this.fragments.length > 0 && this.args.length === 0) {
Could this be simplified to? :

```
        this.args.forEach((value, index) => {
            value = util.quoteArgument(util.resolveVariables(value));
            activeCommand = activeCommand + " " + value;
            this.args[index] = value;
        });
        this.fragments.forEach((value) => {
            activeCommand = activeCommand + " " + value;
            this.args.push(value);
        });
```

Or, as I've suggested before, change `cp.spawn` to `cp.exec`, so we can just pass it `activeCommand`, which we're already building for logging purposes.  Then you could omit all of the edits of `this.args`, reducing that code to:

```
        this.args.forEach((value, index) => {
            value = util.quoteArgument(util.resolveVariables(value));
            activeCommand = activeCommand + " " + value;
        });
        this.fragments.forEach((value) => {
            activeCommand = activeCommand + " " + value;
        });
```

2024-02-23 03:45 UTC, Colengms commented
I think this is the wrong way to go.  I had mentioned another approach in the original issue, to leverage the `command` field.  Doing so would align us with the behavior of VS Code and the default task provider:

https://code.visualstudio.com/docs/editor/tasks

```
{
  "label": "dir",
  "type": "shell",
  "command": "dir 'folder with spaces'"
}
```

```
{
  "label": "dir",
  "type": "shell",
  "command": "dir",
  "args": ["folder with spaces"]
}
```

Ultimately, we may want to support everything they describe there.

2024-02-27 23:59 UTC, closed without merging