adds CHANGELOG entry for PR 2322
microsoft/vscode-cpptools pull request #2325
Opened 2018-07-25 03:59 UTC by john-patterson

Realized I had left out the CHANGELOG update. For [PR 2322](https://github.com/Microsoft/vscode-cpptools/pull/2322).

2018-07-25 04:02 UTC, bobbrow requested changes

2018-07-25 04:02 UTC, bobbrow commented on Extension/CHANGELOG.md
> +* Add multi-pass environment variable resolution allowing variables defined in terms of other variables. [#2322](https://github.com/Microsoft/vscode-cpptools/pull/2322)
We usually just try to do one line per github issue.  I would just keep this first line and remove the rest.

2018-07-25 18:30 UTC, sean-mcmanus commented
What was the 2nd line?

2018-07-25 21:28 UTC, john-patterson commented
@sean-mcmanus I had overwritten it with push -f, I had a line for the following:
```
* Fixed unit test task for VS Code in launch.json.
* Fixed unit test gulp target to be runnable form Travis CI.
* Fixed bug allowing for variables with "env", "config", and "workspaceFolder"
```

2018-07-26 06:04 UTC, bobbrow approved these changes

2018-07-27 16:24 UTC, merged