Update common.ts
microsoft/vscode-cpptools pull request #4658
Opened 2019-11-25 16:57 UTC by dx-coding

This change resolves #4643 and only attempts to update the file permissions if they are not already executable.

2019-11-26 01:13 UTC, Colengms requested changes

2019-11-26 01:13 UTC, Colengms commented on Extension/src/common.ts
> +                if (exists && !isExecutable(file)) {
Since isExecutable() returns a Promise, isn't this "!" checking whether that Promise is null?  I think you'll want something like this:

```
                if (exists) {
                    isExecutable(file).then((isExec: boolean) => {
                        if (isExec) {
                            resolve();
                        } else {
                            fs.chmod(file, '755', (err: NodeJS.ErrnoException) => {
                                if (err) {
                                    reject(err);
                                    return;
                                }
                                resolve();
                            });
                        }
                    });
                } else {
```

It looks like our native binaries are not executable by default in our offline vsix.  (I'll look at fixing that).  Are you setting them as executable manually?

2019-12-02 13:48 UTC, dx-coding commented on Extension/src/common.ts
> +                if (exists && !isExecutable(file)) {
Good point on the Promise, first time looking at JavaScript/Typescript.  Updating, testing and will commit if all appears well.

And yes, in my case I am setting the binaries to executable.

2019-12-02 15:15 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vscode-cpptools?pullRequest=4658) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vscode-cpptools?pullRequest=4658) before we can accept your contribution.<br/><br/>:x: dx-coding [sign now](https://cla.opensource.microsoft.com/microsoft/vscode-cpptools?pullRequest=4658)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vscode-cpptools?pullRequest=4658) it.</sub>

2019-12-02 15:18 UTC, dx-coding commented on Extension/src/common.ts
> +                if (exists && !isExecutable(file)) {
Tested and updated

2019-12-03 03:30 UTC, sean-mcmanus approved these changes

2019-12-03 03:30 UTC, sean-mcmanus commented on Extension/src/common.ts
> +                if (exists && !isExecutable(file)) {
Thanks

2019-12-03 18:29 UTC, Colengms approved these changes

2019-12-05 21:06 UTC, merged