fix Bug 5124, adding namespace indent
microsoft/vscode-cpptools pull request #5150
Opened 2020-03-18 22:18 UTC by elahehrashedi

adding namespace indentation to Visual Studio Clang format style

2020-03-18 22:47 UTC, Colengms approved these changes

2020-03-18 22:51 UTC, sean-mcmanus requested changes
Space before the }

2020-03-19 01:27 UTC, michelleangela commented
Adding reference to issue https://github.com/microsoft/vscode-cpptools/issues/5124

2020-03-19 16:44 UTC, michelleangela approved these changes

2020-03-19 21:10 UTC, sean-mcmanus approved these changes

2020-03-30 17:09 UTC, merged