Add cleanUnusedBinaries stage
microsoft/vscode-cpptools pull request #5153
Opened 2020-03-19 01:12 UTC by WardenGnaw

Our offline installer will include two versions of lldb.
./debugAdapters/lldb is lldb-mi 3.8 and is used for High-Sierra and older
./debugAdapters/lldb-mi is lldb-mi 10.x and is used for Mojave and
higher.

This clean up the folder that is unused. 

Refactored package platform checks to be unified in one area.

2020-03-19 01:25 UTC, sean-mcmanus commented
This just removes the binaries listed in the package.json but keeps both lldb and lldb-mi folders -- is that sufficient for the correct version to get picked up?

2020-03-19 01:30 UTC, WardenGnaw commented
Yes. It is good enough to just remove the binaries. We check the existence via full path.

https://github.com/microsoft/MIEngine/blob/50a932ddbf2f5a10e64aaaf9747a72accca4741e/src/OpenDebugAD7/MILaunchOptions.cs#L466

2020-03-19 01:33 UTC, sean-mcmanus approved these changes

2020-03-19 01:38 UTC, Colengms requested changes
If the user is running an older version of the macOS, then upgrades, will we upgrade to the correct binaries?

2020-03-19 01:44 UTC, sean-mcmanus commented
> If the user is running an older version of the macOS, then upgrades, will we upgrade to the correct binaries?

No, but I think that should be easy to fix -- just add code that uses PersistentState<string> to save and check the OS version -- if it has changed, then run the onlineInstallation().

2020-03-19 04:44 UTC, bobbrow commented on Extension/src/packageManager.ts
> +export function VersionsMatch(pkg: IPackage, info: PlatformInformation): boolean {
Functions should start with a lower case letter.  I know these were previously wrong.  Can you fix them while you're in here?

2020-03-20 00:28 UTC, sean-mcmanus commented
We could add a fix for the "update OS" scenario later on if it can't be done by 0.27.0-insiders4 (on Monday probably).

2020-03-20 01:06 UTC, michelleangela commented on Extension/src/packageManager.ts
> +export function ArchitecturesMatch(value: IPackage, info: PlatformInformation): boolean {
nit: rename "value" to something more distinguishable, like pkg.

2020-03-20 01:09 UTC, michelleangela commented
> We could add a fix for the "update OS" scenario later on if it can't be done by 0.27.0-insiders4 (on Monday probably).

Is the workaround to uninstall and reinstall? Or will something get persisted even if the extension is uninstalled?

2020-03-20 02:15 UTC, sean-mcmanus commented
> We could add a fix for the "update OS" scenario later on if it can't be done by 0.27.0-insiders4 (on Monday probably).
> 
> Is the workaround to uninstall and reinstall? Or will something get persisted even if the extension is uninstalled?

Yeah, uninstall/reinstall of our extension would be a workaround (or updating to a newer version).

2020-03-23 20:10 UTC, merged