Add logging/warnings when compile probing alters explicit user configuration details
microsoft/vscode-cpptools pull request #6180
Opened 2020-09-22 02:46 UTC by Colengms

This is mostly plumbing.  More relevant changes for this are in a PR for the native component.

* Indicates in a configuration if values were explicitly provided by the user.  (Otherwise, they are derived from defaults or other implicit behavior, which would not warrant disturbing the user with a warning).
* Adds some strings for warning/logging (open to input on these).
* Changed c18/gnu18 to c17/gnu17.
* Removed prior fix for detecting compiler filename in environment path.  This is now handled on the native side for all config types.

When combined with the corresponding native PR, addresses: 
* https://github.com/microsoft/vscode-cpptools/issues/6179
* https://github.com/microsoft/vscode-cpptools/issues/6105
* https://github.com/microsoft/vscode-cpptools/issues/6075 
(others)

 I will also have a PR for cpptools-api to make IntelliSenseMode optional from custom config providers, as we can now fully auto-detect it (and don't need to require all custom config providers to replicate that behavior).

2020-09-24 23:07 UTC, michelleangela commented
The cpptools-api will need to know the change of c18 to c17
https://github.com/microsoft/vscode-cpptools-api/blob/ff3a6d2c3c8452df768c2e9381f52c6ed803bd08/api.ts#L162

2020-09-25 20:34 UTC, sean-mcmanus commented on Extension/src/LanguageServer/client.ts
> +        warningChannel = vscode.window.createOutputChannel(`${localize("c.cpp.warnings", "C/C++ Warnings")}`);
Is C/C++ Warnings too vague? It could imply IntelliSense warnings (which aren't enabled yet). Would using C/C++ Configuration Warnings be more clear?

2020-09-25 20:35 UTC, sean-mcmanus approved these changes

2020-09-28 22:16 UTC, sean-mcmanus requested changes

2020-09-28 22:16 UTC, sean-mcmanus commented on Extension/src/nativeStrings.json
> +    "unable_to_configure_cl_exe": "Unable to configure for comppiler cl.exe.",
Spelling comppiler.

2020-09-28 22:32 UTC, sean-mcmanus approved these changes

2020-09-29 00:26 UTC, merged