support yarn pnp for nodeAddonIncludes
microsoft/vscode-cpptools pull request #7123
Opened 2021-03-07 17:35 UTC by Mesteery

This solves problems with Yarn PnP and node addon includes.

⚠️ This has not been tested.

2021-03-08 21:59 UTC, sean-mcmanus commented
Thanks for the contribution. We'll try to review this later this week.

2021-03-09 23:13 UTC, sean-mcmanus requested changes
The stdout I get from yarn is
```
'yarn node v1.19.1\n"<workspaceFolder>\node_modules\\node-addon-api"\nDone in 0.51s.'
```
which isn't processed correctly because the code just expects the middle line. Is that supposed to work correctly and/or how are you getting it to work?

2021-03-10 00:36 UTC, sean-mcmanus commented on Extension/src/LanguageServer/configurations.ts
> +                    nodeAddonMap.push(
Also, this folder/file doesn't exist for me.

2021-03-10 20:25 UTC, Mesteery commented
This is normal, because it's for Yarn Berry.
https://yarnpkg.com/getting-started/install

2021-03-12 02:02 UTC, sean-mcmanus commented
> This is normal, because it's for Yarn Berry.
> https://yarnpkg.com/getting-started/install

Ah, thanks. I'll look into that tomorrow.

2021-03-13 00:34 UTC, sean-mcmanus approved these changes

2021-03-15 21:39 UTC, merged