Update telemetry.ts
microsoft/vscode-cpptools pull request #8243
Opened 2021-10-08 20:18 UTC by jureid

it looks like in [package.json line 5](https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L5), we add a suffix, "main", to the version. When we assign customers to target populations for experiments, we were trying to assign customers without any suffix to Public, which resulted in no one being included. Instead, I think we should be checking if the suffix is "main" and assign those customers to Public.

2021-10-08 20:57 UTC, sean-mcmanus requested changes
What? In general, the only users who should have the main suffix are internal developers. When we build the public vsix, the main is removed.

2021-10-08 21:31 UTC, bobbrow commented
I think the problem is that suffix is `undefined`, not `""`.  Looking at the constructor for PackageVersion, I think that's what's causing problems for you.  Try manually removing the "-main" from package.json for your local testing and you should be able to confirm if that's the case.

2021-10-08 21:56 UTC, bobbrow approved these changes

2021-10-08 22:20 UTC, sean-mcmanus approved these changes

2021-10-12 01:32 UTC, Colengms approved these changes

2021-10-12 23:24 UTC, michelleangela approved these changes

2021-10-12 23:57 UTC, merged