Add svdPath field to OptionsSchema
microsoft/vscode-cpptools pull request #8316
Opened 2021-10-22 15:03 UTC by gcampbell-msft

There is a need to allow for the svdPath field to be set through the launch.json for cppdbg scenarios. This PR will allow for this and allow for intellisense to be active for the svdPath.

2021-10-22 16:20 UTC, bobbrow requested changes

2021-10-22 16:20 UTC, bobbrow commented on Extension/package.nls.json
> +    "c_cpp.debuggers.cppdbg.svdPath.description": "Specifies the path to the users's SVD file.",
typo `user's`

But perhaps we can describe this with a slightly different detail instead.  Would it make sense to say `The full path to an embedded device's SVD file'?  (you can remove the word "specifies" because that is implied already)  I would like for it to reference IoT or embedded devices in some way because many users may have never heard of this file and searching online doesn't bring up relevant results without additional keywords.

2021-10-22 16:20 UTC, bobbrow commented on Extension/package.json
> +    "yarn": "^1.22.15",
Is it necessary to add `yarn` here?  I don't see any dependency changes in this PR.

2021-10-22 16:20 UTC, bobbrow commented on Extension/tools/OptionsSchema.json
> +      "required": ["program"],
Did you format this file and it put the array all on one line?  That seems unusual.  Can you double check?

2021-10-25 16:47 UTC, gcampbell-msft commented on Extension/package.nls.json
> +    "c_cpp.debuggers.cppdbg.svdPath.description": "Specifies the path to the users's SVD file.",
That makes sense, changing now.

2021-10-25 16:49 UTC, gcampbell-msft commented on Extension/package.json
> +    "yarn": "^1.22.15",
You're right, the only change was the svdPath, so no updating of dependencies is necessary.

2021-10-25 16:55 UTC, gcampbell-msft commented on Extension/tools/OptionsSchema.json
> +      "required": ["program"],
I fixed the unnecessary changes.

2021-10-25 17:23 UTC, bobbrow approved these changes

2021-10-28 02:34 UTC, sean-mcmanus approved these changes

2021-10-28 16:02 UTC, merged