Add setting for SwitchHeaderSource UI behavior
microsoft/vscode-cpptools pull request #8857
Opened 2022-02-13 23:57 UTC by joelmsmith

`C_Cpp.SwitchHeaderSource` has different behavior depending on whether the destination file is visible in a different editor pane or not.  This commit adds an option `headerSourcePaneJumping` which controls whether the command will jump to a different editor if the destination file is already visible there.  The default value of true preserves the command's original behavior.

Personally I do not want the default behavior; I want it to simply toggle back and forth between header / source in the same editor that is focused, regardless of what the other ones are displaying.

I'm new to vscode and still finding my way around, so it is likely that I've missed or overlooked something.  Feedback/guidance is welcome.

2022-02-14 20:26 UTC, sean-mcmanus requested changes
Seems fine to me, other than the one comment.

2022-02-14 20:26 UTC, sean-mcmanus commented on Extension/src/LanguageServer/client.ts
> +        const settings_headerSourcePaneJumping: (boolean | undefined)[] = [];
All the edits to client.ts are not needed and should be removed. Those client.ts settings are just for settings which need to be sent to our cpptools process.

2022-02-15 22:41 UTC, sean-mcmanus requested changes

2022-02-15 22:41 UTC, sean-mcmanus commented on Extension/package.json
> +          "scope": "resource"
This should be "application" scope instead of "resource" scope.

2022-02-15 22:53 UTC, sean-mcmanus approved these changes
@bobbrow @jureid Any thoughts on the naming/text?

2022-02-15 22:56 UTC, joelmsmith commented
Hi @sean-mcmanus, thanks for looking at this.  I'm happy to change any of the naming/text if there's a a way to phrase things that better aligns with the project's terminology.

2022-02-16 20:45 UTC, bobbrow commented
Is there any desire for this to be a more general setting to cover any cases where we would open/focus a text editor?  (For example, goto definition)

2022-02-16 21:07 UTC, joelmsmith commented
As far as I can tell, Go to Definition, Go To Declaration, and Go To Type Definition all operate within the focused editor.

2022-02-16 21:17 UTC, bobbrow commented
If the definition is outside the current document, we should be opening a new file.  But I forget whether that is done by vscode or us.

2022-02-16 21:23 UTC, sean-mcmanus requested changes
Instead of adding a new setting, maybe the switching should read the VS Code workbench.editor.revealIfOpen setting? I think that defaults to false. i.e. check the result of vscode.workspace.getConfiguration("workbench.editor.revealIfOpen ".

2022-02-16 21:42 UTC, joelmsmith commented
@sean-mcmanus - I'll take a look at this.  I did not know about this setting, but it sounds like making SwitchHeaderSource obey it will do what I want.
@bobbrow - a new file gets opened (or the tab focused, if it is already opened), but for those 'Go To' commands this happens in the same split (or what the Reval If Open setting refers to as "currently active editor group").

2022-02-18 00:18 UTC, sean-mcmanus approved these changes

2022-02-18 15:52 UTC, bobbrow approved these changes

2022-02-18 15:52 UTC, bobbrow commented on Extension/src/LanguageServer/extension.ts
> +        vscode.window.visibleTextEditors.forEach((editor, index, array) => {
I know you didn't write this code, but if you wouldn't mind updating this line of the lambda to the more concise code below while you're in here, I'd appreciate it.  (totally optional though)
```
vscode.window.visibleTextEditors.forEach(editor => {
```
There's no need to declare `index` and `array`

2022-02-18 20:29 UTC, sean-mcmanus approved these changes

2022-02-18 22:04 UTC, merged