Add global configs
microsoft/vscode-cpptools pull request #9373
Opened 2022-05-27 23:15 UTC by elahehrashedi

2022-05-31 17:34 UTC, jogo- commented on Extension/src/Debugger/configurationProvider.ts
> +    singleFile = "singleFile",              // a debug config defiend for a single mode file
Typo (x4): defiend -> defined

2022-05-31 20:04 UTC, elahehrashedi commented on Extension/src/Debugger/configurationProvider.ts
> +    singleFile = "singleFile",              // a debug config defiend for a single mode file
thank you @jogo-

2022-05-31 21:36 UTC, michelleangela commented on Extension/src/Debugger/configurationProvider.ts
> +         * 1: The configs that comes from playButton and are already defined, these configs should already have their PreLaunchTask defined.
Missing word after "and" in the sentence "The configs that comes from playButton and are already defined, these configs should already have their PreLaunchTask defined."

2022-05-31 21:36 UTC, michelleangela commented on Extension/src/Debugger/configurationProvider.ts
> +         * 2: The configs that comes from debugPanel where the folder is undefined but task can not be found.
Nit: "can not" --> "cannot"

2022-05-31 21:36 UTC, michelleangela commented on Extension/src/Debugger/configurationProvider.ts
> +        // let configs: any = vscode.workspace.getConfiguration('launch', folder).get('configurations');
remove commented code on line 649?

2022-05-31 22:22 UTC, sean-mcmanus commented on Extension/src/Debugger/configurationProvider.ts
> +        /** If the config is coming from "Run and Debug" debugPanel, there are three cases where the folder is undefined:
"from"->"from the"

2022-05-31 22:23 UTC, sean-mcmanus commented on Extension/src/Debugger/configurationProvider.ts
> +         * If the config is coming from "Run and Debug" playButton, there is one case where the folder is undefined:
"from"->"from the"

2022-05-31 22:24 UTC, sean-mcmanus commented on Extension/src/Debugger/configurationProvider.ts
> +        /** Do not resolve PreLaunchTask for these two cases, and let the VsCode resolve it:
"the VsCode"->"VS Code" or "vscode"

2022-05-31 22:27 UTC, sean-mcmanus commented on Extension/src/Debugger/configurationProvider.ts
> +            // Send Telemetry before writing into files.
"Telemetry"->"telemetry"

2022-05-31 22:30 UTC, michelleangela requested changes

2022-05-31 22:30 UTC, michelleangela commented on Extension/src/Debugger/configurationProvider.ts
> +        if (matchingConfig && matchingConfig.source) {
Simplify `if (matchingConfig && matchingConfig.source)` to `if (matchingConfig?.source)` ?

2022-05-31 22:31 UTC, sean-mcmanus requested changes

2022-05-31 22:31 UTC, sean-mcmanus commented on Extension/src/LanguageServer/cppBuildTaskProvider.ts
> +        const selectedTask: any = rawTasksJson.tasks.find((task: any) => task.label && task.label === taskLabel);
Can this be simplified to 1 return line, e.g. `return rawTasksJson...`?

2022-06-01 17:48 UTC, michelleangela approved these changes

2022-06-01 20:09 UTC, sean-mcmanus approved these changes

2022-06-01 22:34 UTC, merged